### ISSUE TITLE
Missing StringIO import from ftp.py

### ISSUE THREAD

**Issue by mocsar** [Lukasa/requests-ftp#14]
Import is missing from ftp.py:
from StringIO import StringIO

**Comment by aidanlister** [comment]
No python3 support :(

**Comment by Lukasa** [comment]
Can I see the full traceback, please?

**Comment by mocsar** [comment]
nlst works what uses BytesIO.

I get this if I use list:

Traceback (most recent call last):
  File "C:/Users/mocsar/projects/bg-py/bg-converter/src/main.py", line 68,
in <module>
    main()
  File "C:/Users/mocsar/projects/bg-py/bg-converter/src/main.py", line 57,
in main
    new_files = lst()
  File "C:/Users/mocsar/projects/bg-py/bg-converter/src/main.py", line 19,
in lst
    resp = s.list('ftp://{}/guglik/'.format(host))
  File "C:\Python27\lib\site-packages\requests_ftp\ftp.py", line 25, in list
    return self.request('LIST', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in
request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in
send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests_ftp\ftp.py", line 182, in
send
    resp = self.func_table[request.method](path, request)
  File "C:\Python27\lib\site-packages\requests_ftp\ftp.py", line 234, in
list
    data = StringIO()
NameError: global name 'StringIO' is not defined

**Comment by Lukasa** [comment]
Hmm: are you using the most recent version?

**Comment by Lukasa** [comment]
Ah, I see, this is fixed in master, I just need to push a new release. Whoops!

**Comment by Lukasa** [comment]
Should be fixed in v0.3.1.
